version: '3.9'
volumes:
  # volume mount storage
  # コンテナを立ち上げるほどじゃない、downした時に消えてほしくないもの（DBとか）
  # NASみたいな、ストレージ領域（箱）を作る
  # これを経由してソケット通信
  php-socket:
  # 追記
  db-store:

services:
  web:
    build:
      context: .
      # ここをcurrentとする
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/work
      # travelogと同期させてる
      - php-socket:/var/run/php-fpm
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      # ソケットで通信してるからポートは書かない
    volumes:
      - ./:/work
      - php-socket:/var/run/php-fpm
  # 追記
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5432:5432
